### ISSUE TITLE
Twitter link previews broken again

### ISSUE THREAD

**Issue by feld** [wireapp/wire-ios-link-preview#59]
They appear to be broken again.

Based on my research it seems back in Feb they started filtering on User Agent, which you fixed in #56.

Early June the link previews broke for Whatsapp and they reached out to a twitter PM and it was "fixed". https://twitter.com/wcathcart/status/1267836549233704960

I think Twitter's now only allowing OpenGraph tags to requests from specific address space. As WireApp makes the request from the client, this breaks for you. It also breaks for other open source projects I'm involved in.

If you have any information please share it. I'll do my best to reciprocate.

**Comment by feld** [comment]
This is fixed if you change your UA to have "bot" in the name, or impersonate WhatsApp. Here are the real UAs used by others where it still works:

Whatsapp: **WhatsApp/2.20.70 i**   (WhatsApp as a bareword, case sensitive, works too)
Telegram: **TelegramBot (like TwitterBot)**
iMessage: **Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0**

**Comment by typfel** [comment]
Thanks for the info!
